import { useEffect, useState } from 'react';
import { IonContent, IonButton, IonList, IonItem, IonToast, IonInput, IonSelect, IonTextarea, IonNote, IonSelectOption, useIonViewWillEnter, useIonViewWillLeave, IonPage, IonIcon, IonText } from '@ionic/react';
import './ItemPage.css';
import { Maintenance, MaintenanceType, maintenanceTypes } from '../models/MaintenanceType';
import DataPickerPopup from '../components/DataPickerPopup';
import { Header } from '../components/Header';

import { useLocation } from 'react-router-dom';
import { getDateString, getUUIDKey, parseStringToDate } from '../services/utils';
import { useMaintenanceDb } from '../hooks/useDbContext';
import { add, pencilOutline } from 'ionicons/icons';

interface MaintenanceState {
  item: Maintenance;
}

function ItemPage() {

  // https://stackoverflow.com/a/59464381/4700162
  const location = useLocation<MaintenanceState>();
  console.log(location.state?.item)

  console.log('Rendering NewItem component');
  const db = useMaintenanceDb();
  const [isSuccess, setIsSuccess] = useState(false);

  const currentDate = getDateString();
  const [formData, setFormData] = useState<Maintenance>({
    data: currentDate,
    km: 0,
    tipo: 'Tagliando' as MaintenanceType,
    costo: 0,
    note: '',
  });

  const [didEdit, setDidEdit] = useState({
    data: false,
    km: false,
    tipo: false,
    costo: false,
    note: false,
  });

  const formatCost = (value: string): string => {
    return value.replace('.', ',');
  };

  const isKmInvalid = didEdit.km && (Number(formData.km) === 0 || Number(formData.km) > 999999);
  const isCostoInvalid = didEdit.costo && (Number(formData.costo) === 0 || Number(formData.costo) > 999999);



  const handleAddMaintenance = async (newMaintenance: Maintenance) => {

    db.put(newMaintenance).then((response) => {
      console.log('Maintenance added successfully:', response);
    }).catch((error) => {
      console.error('Error adding maintenance:', error);
    });

  };




  const handleInputChange = (inputIdentifier: any, newValue: any) => {
    if (inputIdentifier === 'data') {
      console.log('handleInputChange data', newValue);
      newValue = getDateString(newValue as Date);
    }

    if (inputIdentifier === 'costo') {
      newValue = formatCost(newValue);
    }

    setFormData((prevState) => ({
      ...prevState,
      [inputIdentifier]: newValue,
    }));

    setDidEdit((prevEdit) => ({
      ...prevEdit,
      [inputIdentifier]: true,
    }));
  };

  const handleSubmit = async (event: any) => {
    event.preventDefault();
    try {
      const newMaintenance: Maintenance = {
        _id: getUUIDKey(), // do not care about the id value (generated by sqlite)
        data: getDateString(parseStringToDate(formData.data)),
        km: Number(formData.km) || 0,
        tipo: formData.tipo as MaintenanceType,
        costo: Number(formData.costo) || 0,
        note: formData.note || '',
      };
      console.log('newMaintenance', newMaintenance);

      handleAddMaintenance(newMaintenance);
      setIsSuccess(prevValue => !prevValue)
    } catch (error) {
      setIsSuccess(false);
      console.error('Errore nel salvataggio:', error);
    }
  };

  const handleInputBlur = (identifier: any) => {
    setDidEdit((prevEdit) => ({
      ...prevEdit,
      [identifier]: true,
    }));
  }


  useIonViewWillLeave(() => {
    setFormData({
      data: currentDate,
      km: 0,
      tipo: 'Tagliando' as MaintenanceType,
      costo: 0,
      note: '',
    });
    setIsSuccess(false);
    setDidEdit({
      data: false,
      km: false,
      tipo: false,
      costo: false,
      note: false,
    })
  });


  useEffect(() => {
    if (location.state?.item) {
      setFormData({
        _id: location.state.item._id,
        _rev: location.state.item._rev || undefined,
        data: location.state.item.data,
        km: location.state.item.km,
        tipo: location.state.item.tipo as MaintenanceType,
        costo: location.state.item.costo,
        note: location.state.item.note || ''
      });
    }
  }, [location.state?.item])



  return (
    <IonPage>
      <Header title="Aggiungi Manutenzione" />
      <IonContent color="light">
        <IonList inset={true}>
          <IonItem lines="inset" slot="header">
            <DataPickerPopup title="Scegli data" currentDate={formData.data} onChange={handleInputChange} />
          </IonItem>
          <IonItem>
            <IonInput
              labelPlacement="floating"
              label="KM"
              type="number"
              name="km"
              onBlur={() => handleInputBlur('km')}
              value={formData.km}
              onIonChange={(e) => handleInputChange('km', e.detail.value)}
              min={0}
              max={999999}
            />
          </IonItem>
          <div style={{ padding: '0 16px' }}>
            <IonText color="danger" style={{ fontSize: '0.8em' }}>
              {isKmInvalid && <p style={{ margin: '4px 0' }}>
                Per favore inserisci un costo superiore a 0.
              </p>}
            </IonText>
          </div>
          <IonItem>
            <IonInput
              labelPlacement="floating"
              label="Costo (€)"
              type="text"
              inputmode="decimal"
              name="costo"
              onBlur={() => handleInputBlur('costo')}
              value={formData.costo}
              onIonChange={(e) => handleInputChange('costo', e.detail.value)}
              min={0}
              max={999999}
            />
          </IonItem>
          <div style={{ padding: '0 16px' }}>
            <IonText color="danger" style={{ fontSize: '0.8em' }}>
              {isCostoInvalid && <p style={{ margin: '4px 0' }}>
                Per favore inserisci un costo superiore a 0.
              </p>}
            </IonText>
          </div>
          <IonItem lines="inset" slot="header">
            <IonSelect
              labelPlacement="floating"
              label="Tipo"
              aria-label="Maintenance"
              interface="action-sheet"
              placeholder="Select Maintenance"
              name="type"
              value={formData.tipo}
              onBlur={() => handleInputBlur('tipo')}
              onIonChange={(e) => handleInputChange('tipo', e.detail.value)}>
              {maintenanceTypes.map((type) => (
                <IonSelectOption key={type} value={type}>
                  {type}
                </IonSelectOption>
              ))}
            </IonSelect>
          </IonItem>
        </IonList>
        <IonNote color="medium" class="ion-margin-horizontal">
          Aggiungi eventuali note.
        </IonNote>
        <IonList inset={true}>
          <IonItem>
            <IonTextarea label="Commento" label-placement="floating" value={formData.note} rows={5} onIonChange={(e) => handleInputChange('note', e.detail.value)}></IonTextarea>
          </IonItem>
        </IonList>

        {location.state?.item ?
          <IonButton id="open-toast" expand="full" className="buttonAddList" onClick={handleSubmit} disabled={isCostoInvalid || isCostoInvalid}>
            <IonIcon slot="icon-only" ios={pencilOutline} md={pencilOutline}></IonIcon>
            Modifica Manutenzione
          </IonButton>
          :
          <IonButton id="open-toast" expand="full" className="buttonAddList" onClick={handleSubmit} disabled={isCostoInvalid || isCostoInvalid}>
            <IonIcon slot="icon-only" ios={add} md={add}></IonIcon>
            Aggiungi Manutenzione
          </IonButton>
        }

        <IonToast
          isOpen={isSuccess}
          onDidDismiss={() => setIsSuccess(prevValue => !prevValue)}
          message={isSuccess ? "Manutenzione aggiunta con successo!" : "Errore durante l'aggiunta della manutenzione"}
          duration={3000}
          color={isSuccess ? "success" : "danger"}
        />
      </IonContent>
    </IonPage>
  );
}

export default ItemPage;
