import React, { useState, useContext, useRef, useEffect } from 'react';
import { IonContent, IonButton, IonList, IonItem, IonToast, IonInput, IonSelect, IonTextarea, IonNote, IonSelectOption, useIonViewWillEnter, useIonViewWillLeave, IonPage } from '@ionic/react';
import './ItemPage.css';
import { Maintenance, MaintenanceType, maintenanceTypes } from '../models/Maintenance';
import DataPickerPopup from '../components/DataPickerPopup';
import { Header } from './Header';
import { getEnv } from '../services/env';
import { PouchDbService } from '../services/pouchDbService';

const envVar = getEnv();

function ItemPage() {

  console.log('Rendering NewItem component');

  const [isSuccess, setIsSuccess] = useState(false);
  const [db, setDb] = useState<any>(null);

  useEffect(() => {
    const database = PouchDbService.getInstance(envVar?.car_table);
    setDb(database);
  }, []);

  const currentDate = new Date().toLocaleDateString('it-IT', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  const [formData, setFormData] = useState({
    data: currentDate,
    km: 0,
    tipo: 'Tagliando' as MaintenanceType,
    costo: 0,
    note: '',
  });



  const handleAddMaintenance = async (newMaintenance: Maintenance) => {

    db.getInfo().then((info) => {
      console.log('Database info:', info);
    })

    const example = {
      _id: newMaintenance.id.toString(),
      ...newMaintenance
    }

    db.getDatabase().put(example).then((response) => {
      console.log('Maintenance added successfully:', response);
    }).catch((error) => {
      console.error('Error adding maintenance:', error);
    });

    const res = db.getDatabase().allDocs({ include_docs: true }).then((result: any) => {
      console.log("RESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS")
      console.log(result.rows);
    })


    setFormData({
      data: currentDate,
      km: 0,
      tipo: 'Tagliando',
      costo: 0,
      note: '',
    });


  };




  const handleInputChange = (inputIdentifier: any, newValue: any) => {
    if (inputIdentifier === 'data') {
      const selectedDate = new Date(newValue).toLocaleDateString('it-IT', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      });
      newValue = selectedDate;
    }

    setFormData((prevState) => ({
      ...prevState,
      [inputIdentifier]: newValue,
    }));
  };

  const handleSubmit = async (event: any) => {
    event.preventDefault();
    try {
      console.log("PROVA")
      const newMaintenance: Maintenance = {
        id: Date.now(), // do not care about the id value (generated by sqlite)
        data: formData.data,
        km: formData.km,
        tipo: formData.tipo,
        costo: formData.costo,
        note: formData.note,
      };

      console.log('newMaintenance', newMaintenance);

      handleAddMaintenance(newMaintenance);
      console.log("PROVA2")
      setIsSuccess(true);
    } catch (error) {
      setIsSuccess(false);
      console.error('Errore nel salvataggio:', error);
    }
  };




  return (
    <>
      <Header title="Maintenance" />
      <IonContent color="light">
        <IonList inset={true}>
          <IonItem lines="inset" slot="header">
            <DataPickerPopup title="Scegli data" currentDate={formData.data} onChange={handleInputChange} />
          </IonItem>
          <IonItem>
            <IonInput
              labelPlacement="floating"
              label="KM"
              type="number"
              name="km"
              value={formData.km}
              onIonChange={(e) => handleInputChange('km', e.detail.value)}
              min={0}
            />
          </IonItem>
          <IonItem>
            <IonInput
              labelPlacement="floating"
              label="Costo (€)"
              type="number"
              name="costo"
              value={formData.costo}
              onIonChange={(e) => handleInputChange('costo', e.detail.value)}
              min={0}
            />
          </IonItem>
          <IonItem lines="inset" slot="header">
            <IonSelect
              labelPlacement="floating"
              label="Tipo"
              aria-label="Maintenance"
              interface="action-sheet"
              placeholder="Select Maintenance"
              name="type"
              value={formData.tipo}
              onIonChange={(e) => handleInputChange('tipo', e.detail.value)}>
              {maintenanceTypes.map((type) => (
                <IonSelectOption key={type} value={type}>
                  {type}
                </IonSelectOption>
              ))}
            </IonSelect>
          </IonItem>
        </IonList>
        <IonNote color="medium" class="ion-margin-horizontal">
          Aggiungi eventuali note.
        </IonNote>
        <IonList inset={true}>
          <IonItem>
            <IonTextarea label="Comments" label-placement="floating" rows={5} onIonChange={(e) => handleInputChange('note', e.detail.value)}></IonTextarea>
          </IonItem>
        </IonList>
        <IonButton id="open-toast" expand="full" className="buttonAddList" onClick={handleSubmit}>
          Aggiungi Manutenzione
        </IonButton>

        {isSuccess ? (
          <IonToast trigger="open-toast" color="success" style={{ text: 'white' }} message="Manutenzione aggiunta con successo!" duration={5000}></IonToast>
        ) : (
          <IonToast trigger="open-toast" color="danger" message="Errore durante l'aggiunta della manutenzione" duration={1000}></IonToast>
        )}
      </IonContent>
    </>
  );
}

export default ItemPage;
