import React, { useState, useContext } from 'react';
import { IonContent, IonButton, IonList, IonItem, IonToast, IonInput } from '@ionic/react';
import './ItemPage.css';
import DataPickerPopup from '../components/DataPickerPopup';
import { Header } from './Header';
import { DbLastKmContext } from '../App';
import { useLocation, useParams } from 'react-router-dom';
import { LastKm } from '../models/LastKmType';
import { getDateString } from '../services/utils';

interface KmState {
  item: LastKm;
}

function KmPage() {

  // https://stackoverflow.com/a/59464381/4700162
  const location = useLocation<KmState>();
  console.log(location.state?.item)

  console.log('Rendering NewItem component');
  const dbKm = useContext(DbLastKmContext);
  const [isSuccess, setIsSuccess] = useState(false);

  const currentDate = getDateString();
  const [formData, setFormData] = useState(() => {

    if (location.state?.item) {
      // aggiornamento
      return {
        data: location.state.item.data,
        km: location.state.item.km
      };
    }

    return {
      data: currentDate,
      km: 0,
    }
  });



  const handleAddKm = async (newKm: LastKm) => {

    dbKm.getInfo().then((info) => {
      console.log('Database info:', info);
    })



    dbKm.put(newKm).then((response) => {
      console.log('Maintenance added successfully:', response);
    }).catch((error) => {
      console.error('Error adding maintenance:', error);
    });

    const res = dbKm.allDocs({ include_docs: true }).then((result: any) => {
      console.log(result.rows);
    })

    setFormData({
      data: currentDate,
      km: 0
    });
  };




  const handleInputChange = (inputIdentifier: any, newValue: any) => {
    if (inputIdentifier === 'data') {
      const selectedDate = new Date(newValue).toLocaleDateString('it-IT', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      });
      newValue = selectedDate;
    }

    setFormData((prevState) => ({
      ...prevState,
      [inputIdentifier]: newValue,
    }));
  };

  const handleSubmit = async (event: any) => {
    event.preventDefault();
    try {
      console.log("PROVA")
      const lastKm: LastKm = {
        _id: String(Date.now()), // do not care about the id value (generated by sqlite)
        data: formData.data,
        km: formData.km,
      };

      console.log('lastKm', lastKm);

      handleAddKm(lastKm);
      console.log("PROVA2")
      setIsSuccess(true);
    } catch (error) {
      setIsSuccess(false);
      console.error('Errore nel salvataggio:', error);
    }
  };




  return (
    <>
      <Header title="Maintenance" />
      <IonContent color="light">
        <IonList inset={true}>
          <IonItem lines="inset" slot="header">
            <DataPickerPopup title="Scegli data" currentDate={formData.data} onChange={handleInputChange} />
          </IonItem>
          <IonItem>
            <IonInput
              labelPlacement="floating"
              label="KM"
              type="number"
              name="km"
              value={formData.km}
              onIonChange={(e) => handleInputChange('km', e.detail.value)}
              min={0}
            />
          </IonItem>
        </IonList>
        {location.state?.item ?
          <IonButton id="open-toast" expand="full" className="buttonAddList" onClick={handleSubmit}>
            Modifica Kilometraggio
          </IonButton>
          :
          <IonButton id="open-toast" expand="full" className="buttonAddList" onClick={handleSubmit}>
            Aggiungi Kilometraggio
          </IonButton>
        }

        {isSuccess ? (
          <IonToast trigger="open-toast" color="success" style={{ text: 'white' }} message="Kilometraggio aggiunto con successo!" duration={5000}></IonToast>
        ) : (
          <IonToast trigger="open-toast" color="danger" message="Errore durante l'aggiunta del Kilometraggio" duration={1000}></IonToast>
        )}
      </IonContent>
    </>
  );
}

export default KmPage;
