import { useState } from 'react';
import { IonToast, useIonViewWillLeave, IonPage } from '@ionic/react';
import './ItemPage.css';
import { Maintenance } from '../models/MaintenanceType';
import { Header } from '../components/Header';
import { useMaintenanceDb } from '../hooks/useDbContext';
import { FormMaintenance } from '../components/FormMaintenance';

const NewMaintenance = () => {
  const db = useMaintenanceDb();
  const [toastOpen, setToastOpen] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);

  const handleAddMaintenance = async (maintenance: Maintenance) => {
    db.put(maintenance)
      .then((response) => {})
      .catch((error) => {
        console.error('Error adding maintenance:', error);
      });
  };

  const handleSubmit = async (formData: Maintenance) => {
    try {
      // let mnt: Maintenance;

      // if (editingItem && editingItem._rev) {
      //   mnt = {
      //     _id: editingItem._id, // do not care about the id value (generated by sqlite)
      //     _rev: editingItem._rev,
      //     data: getDateString(parseStringToDate(formData.data)),
      //     km: Number(formData.km) || 0,
      //     tipo: formData.tipo as MaintenanceType,
      //     costo: Number(formData.costo) || 0,
      //     note: formData.note || '',
      //   };
      //
      // } else {
      //   mnt = {
      //     _id: editingItem ? editingItem._id : getUUIDKey(), // do not care about the id value (generated by sqlite)
      //     data: getDateString(parseStringToDate(formData.data)),
      //     km: Number(formData.km) || 0,
      //     tipo: formData.tipo as MaintenanceType,
      //     costo: Number(formData.costo) || 0,
      //     note: formData.note || '',
      //   };
      //
      // }

      handleAddMaintenance(formData).then(() => {
        setIsSuccess((prevValue) => !prevValue);
      });
    } catch (error) {
      setIsSuccess(false);
      console.error('Errore nel salvataggio:', error);
    } finally {
      setToastOpen(true);
    }
  };

  useIonViewWillLeave(() => {
    setIsSuccess(false);
  });

  // useEffect(() => {
  //   if (editingItem) {
  //
  //
  //     setFormData({
  //       _id: editingItem._id,
  //       _rev: editingItem._rev || undefined,
  //       data: editingItem.data,
  //       km: editingItem.km,
  //       tipo: editingItem.tipo as MaintenanceType,
  //       costo: editingItem.costo,
  //       note: editingItem.note || '',
  //     });
  //   }
  // }, [editingItem]);

  return (
    <IonPage>
      <Header title="Aggiungi Manutenzione" />

      <FormMaintenance onSubmit={handleSubmit}>
        <IonToast
          isOpen={toastOpen && isSuccess}
          onDidDismiss={() => setToastOpen(false)}
          color="success"
          message="Manutenzione aggiunta con successo!"
          duration={1000}
        />

        <IonToast
          isOpen={toastOpen && !isSuccess}
          onDidDismiss={() => setToastOpen(false)}
          color="danger"
          message="Errore durante l'aggiunta della manutenzione"
          duration={1000}
        />
      </FormMaintenance>
    </IonPage>
  );
};

export default NewMaintenance;
